src/accounts/urls.py
from django.urls import path, re_path

from .views import (
        AccountHomeView,
        AccountUsernameActivateView,
        UserDetailUpdateView,
        AllUsersView
)

app_name = 'account'

urlpatterns = [
    path('', UserDetailUpdateView.as_view(), name='home'),
    path('all/', AllUsersView.as_view(), name='all'),
    path('all/user-<slug:id>', UserDetailUpdateView.as_view(), name='user_detail'),
    re_path('username/confirm/(?P<key>[0-9A-Za-z]+)/', AccountUsernameActivateView.as_view(), name='username_activate'),
    re_path('username/resend_activation/', AccountUsernameActivateView.as_view(), name='resend_activation'),
]

src/carts/urls.py
from django.urls import path

from .views import (
        CartView,
        # CartRemoveView,
        # cart_add,
        cart_field_change,
        set_company,
        cart_remove,
        checkout_home,
        clean_date,
        validate_quantity
)

app_name = 'cart'

urlpatterns = [
    # path('', cart_home, name='home'),
    path('', CartView.as_view(), name='home'),
    # path('add/', cart_add, name='add'),
    path('checkout/', checkout_home, name='checkout'),
    # path('remove/', CartRemoveView.as_view(), name='remove'),
    path('cart_field_change/', cart_field_change, name='field_change'),
    path('clean_date/', clean_date, name='clean_date'),
    path('set_company/', set_company, name='set_company'),
    path('remove/', cart_remove, name='remove'),
    path('validate_quantity/', validate_quantity, name='validate'),
]

src/posts/urls.py
from django.urls import path

from .views import (
    PostView,
    post_add,
    post_remove
)

app_name = 'post'

urlpatterns = [
    path('', PostView.as_view(), name='home'),
    path('add/', post_add, name='add'),
    path('remove/', post_remove, name='remove'),
]

src/products/urls.py
from django.urls import path

from .views import (
    ProductListView,
    ProductDetailView,
    ProductDetailUpdateView,
    cart_add
)


app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:company>/', ProductListView.as_view(), name='company_products'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='detail'),
    path('<slug:slug>/edit/', ProductDetailUpdateView.as_view(), name='edit'),
    path('cart/add/', cart_add, name='add'),
    path('<slug:slug>/cart/add/', cart_add, name='add_to_cart'),

    # path('<int:company>/cart/add/', cart_add, name='add_to_cart'),
    # path('<int:company>/<slug:slug>/cart/add/', cart_add, name='add_to_cart'),

]

src/tfl/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from .views import home_page
from accounts.views import LoginView, RegisterView
from products.views import ProductAddView
from dashboard.views import DashboardView, DashboardDataApiView


urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('add_product/', ProductAddView.as_view(), name='add_product'),
    path('api/dashboard/', DashboardDataApiView.as_view(), name='dashboard-api'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('register/', RegisterView.as_view(), name='register'),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

src/templates/base/footer.html
<footer class="footer fixed-bottom mt-auto py-2 bg-dark text-white text-center">
    <div class="container">
        <span class="text-muted">Task Force & Logistic</span>
    </div>
</footer>

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

<!-- Chart.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>

<!-- My JS file -->
<script src="{% static "js/tfl.js" %}"></script>

src/templates/base/navbar.html
{% load static %}

{% url 'post:home' as home_url %}
{% url 'account:all' as all_users_url %}
{% url 'companies:home' as companies_url %}
{% url 'companies:add' as add_company_url %}
{% url 'add_product' as add_product_url %}
{% url 'login' as login_url %}
{% url 'dashboard' as dashboard_url %}
{% url 'logout' as logout_url %}
{% url 'orders:home' as order_list_url %}
{% url 'register' as register_url %}
{% url 'products:list' as product_list_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}
{% url "password_change" as password_change_url %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class='container'>
      <a class="navbar-brand" href="{{ home_url }}">
        <img src="{% static 'img/tforce_logo.png' %}" width="40" height="46" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if request.path == home_url %}active{% endif %}">
            <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if request.path == product_list_url %}active{% endif %} dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="catalogs" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Catalogs
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for cm in  companies_menu  %}
                    <a class="dropdown-item" href="{% url 'products:company_products' cm.id %}">{{ cm.name }}</a>
                {% endfor %}
                {% if companies_menu %}
                    <div class="dropdown-divider"></div>
                {% endif %}
              <a class="dropdown-item" href="{{ product_list_url }}" id="000">All Products</a>
            </div>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ account_url }}">Detail</a>
              <a class="dropdown-item" href="{{ order_list_url }}">
                Orders
{#                <span class="badge badge-dark">{{request.session.orders|default:0}}</span>#}
              </a>
              <a class="dropdown-item" href="{{ password_change_url }}">Change Password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
            </div>
          </li>
              {% if request.user.is_staff or request.user.is_admin %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Staff
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ add_product_url }}">Add Product</a>
                  <a class="dropdown-item" href="{{ companies_url }}">Companies</a>
                  <a class="dropdown-item" href="{{ add_company_url }}">Add Company</a>
                  <a class="dropdown-item" href="{{ all_users_url }}">Users</a>
                </div>
              </li>
              {% endif %}
              {% if request.user.is_admin %}
                  <li class="nav-item {% if request.path == dashboard_url %}active{% endif %}">
                    <a class="nav-link" href="{{ dashboard_url }}">Dashboard</a>
                  </li>
              {% endif %}
          {% endif %}

        </ul>
        <ul class="navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{{ cart_url }}">
              <span class="badge badge-dark" id="cart_count">{{request.session.cart_items|default:0}}</span>
              <i class="fas fa-shopping-cart"></i>
            </a>
          </li>
          {% else %}
          <!--<li class="nav-item ml-5 {% if request.path == login_url %}active{% endif %}">-->
            <!--<a class="nav-link" href="{{ login_url }}">Login</a>-->
          <!--</li>-->
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <!--<a class="nav-link" data-toggle="modal" data-target="#loginRegisterModal">Login/Register</a>   -->
            <a class="nav-link" href="{{ login_url }}">Login</a>
          </li>
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link" href="{{ register_url }}">Register</a>
          </li>
          <!--<li class="nav-item ml-5 {% if request.path == register_url %}active{% endif %}">-->
            <!--<a class="nav-link" href="{{ register_url }}">Register</a>-->
          <!--</li>-->
          {% endif %}
        </ul>
      </div>
    </div>
</nav>