src/carts/urls.py
from django.urls import path

from .views import (
        CartView,
        # CartRemoveView,
        # cart_add,
        cart_field_change,
        set_company,
        cart_remove,
        checkout_home,
        clean_date,
        validate_quantity
)

app_name = 'cart'

urlpatterns = [
    # path('', cart_home, name='home'),
    path('', CartView.as_view(), name='home'),
    # path('add/', cart_add, name='add'),
    path('checkout/', checkout_home, name='checkout'),
    # path('remove/', CartRemoveView.as_view(), name='remove'),
    path('cart_field_change/', cart_field_change, name='field_change'),
    path('clean_date/', clean_date, name='clean_date'),
    path('set_company/', set_company, name='set_company'),
    path('remove/', cart_remove, name='remove'),
    path('validate_quantity/', validate_quantity, name='validate'),
]

src/orders/urls.py
from django.urls import path

from .views import (
        AllOrdersView,
        OrderDetailView,
        order_confirm,
        order_edit
)

app_name = 'orders'

urlpatterns = [
    path('', AllOrdersView.as_view(), name='home'),
    path('<slug:id>/', OrderDetailView.as_view(), name='detail'),
    path('<slug:id>/confirm/', order_confirm, name='confirm'),
    path('<slug:id>/edit_order/', order_edit, name='edit'),
    # path('confirm/', order_confirm, name='confirm'),
]

src/tfl/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from .views import home_page
from accounts.views import LoginView, RegisterView
from products.views import ProductAddView
from dashboard.views import DashboardView, DashboardDataApiView


urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('add_product/', ProductAddView.as_view(), name='add_product'),
    path('api/dashboard/', DashboardDataApiView.as_view(), name='dashboard-api'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('register/', RegisterView.as_view(), name='register'),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.db.models import Q

from carts.models import Cart
from tfl.utils import unique_order_id_generator

User = settings.AUTH_USER_MODEL

ORDER_STATUS_CHOICES = (
    ('created', 'Created'),
    ('confirm', 'Confirm'),
    ('canceled', 'Canceled')
)


class OrderQuerySet(models.query.QuerySet):
    def all(self):
        return self.filter(active=True).order_by('-timestamp')

    def my_orders(self, user):
        lookups = (Q(cart__user=user) &
                   Q(active=True)
                   )
        return self.filter(lookups).order_by('-timestamp')

    def company_orders(self, company):
        lookups = (Q(cart__company=company) &
                   Q(active=True)
                   )
        return self.filter(lookups).order_by('-timestamp')

    def by_cart_products(self, cart_products_obj):
        lookups = (Q(cart__products__in=cart_products_obj) &
                   Q(active=True))

        return self.filter(lookups)

    def cp_exist(self, order, cart_product):
        lookups = (Q(id=order.id) & Q(cart__products=cart_product))

        qs = self.filter(lookups)
        if qs.count() == 1:
            return True
        return False


class OrderManager(models.Manager):
    def get_queryset(self):
        return OrderQuerySet(self.model, using=self._db)

    def my_orders(self, user):
        return self.get_queryset().my_orders(user)

    def company_orders(self, user):
        company = user.company
        return self.get_queryset().company_orders(company)

    def get_by_company(self, company):
        return self.get_queryset().company_orders(company)

    def all(self, user):
        if user.is_staff or user.is_admin:
            return self.get_queryset().all()
        else:
            return self.company_orders(user)

    def get_by_cart_products(self, cart_products_obj):
        return self.get_queryset().by_cart_products(cart_products_obj)

    def cp_exist(self, order, cart_product):
        return self.get_queryset().cp_exist(order, cart_product)


class Order(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    order_id = models.CharField(max_length=120, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, default='created', choices=ORDER_STATUS_CHOICES)
    total_price = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total_weight = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = OrderManager()

    def __str__(self):
        return self.order_id

    def get_absolute_url(self):
        return reverse('orders:detail', kwargs={'id': self.id})

    def update_total(self):
        self.total_price = self.cart.total_price
        self.total_weight = self.cart.total_weight
        self.save()

    def deactivate(self):
        self.active = False
        self.save()


def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)


pre_save.connect(pre_save_create_order_id, sender=Order)


def post_save_cart_total(sender, instance, created, *args, **kwargs):
    if not created:
        cart_obj = instance
        cart_id = cart_obj.id
        qs = Order.objects.filter(cart__id=cart_id)
        if qs.count() == 1:
            order_obj = qs.first()
            order_obj.update_total()


post_save.connect(post_save_cart_total, sender=Cart)


def post_save_order(sender, instance, created, *args, **kwargs):
    if created:
        instance.update_total()


post_save.connect(post_save_order, sender=Order)

src/orders/forms.py
import datetime

from django import forms
from tempus_dominus.widgets import DateTimePicker

from companies.models import Company


class OrderForm(forms.Form):
    manifestation = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-1',
               'id': 'inputManifestation',
               'placeholder': 'Manifestation',
               }
    ), label='', disabled=True)
    address = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-1',
               'id': 'inputAddress',
               'placeholder': 'Address',
               }
    ), label='', disabled=True)
    beginning = forms.CharField(widget=DateTimePicker(
        options={
            'minDate': (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),  # Tomorrow
            'useCurrent': False,
            'collapse': False,
            'format': 'DD/MM/YYYY HH:mm'
        },
        attrs={'class': 'form-control',
               'id': 'inputBiginning',
               'placeholder': 'Beginning Date',
               'append': 'fa fa-calendar',
               'input_toggle': True,
               'icon_toggle': True,
               }
    ), label='', disabled=True)
    ending = forms.CharField(widget=DateTimePicker(
        options={
            'minDate': (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),  # Tomorrow
            'useCurrent': False,
            'collapse': False,
            'format': 'DD/MM/YYYY HH:mm'
        },
        attrs={'class': 'form-control',
               'id': 'inputEnding',
               'placeholder': 'Ending Date',
               'append': 'fa fa-calendar',
               'input_toggle': True,
               'icon_toggle': True,
               }
    ), label='', disabled=True)
    delivery = forms.CharField(widget=DateTimePicker(
        options={
            'minDate': (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),  # Tomorrow
            'useCurrent': False,
            'collapse': False,
            'format': 'DD/MM/YYYY HH:mm'
        },
        attrs={'class': 'form-control',
               'id': 'inputDelivery',
               'placeholder': 'Delivery Date',
               'append': 'fa fa-calendar',
               'input_toggle': True,
               'icon_toggle': True,
               }
    ), label='', disabled=True)
    pickup = forms.CharField(widget=DateTimePicker(
        options={
            'minDate': (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),  # Tomorrow
            'useCurrent': False,
            'collapse': False,
            'format': 'DD/MM/YYYY HH:mm'
        },
        attrs={'class': 'form-control',
               'id': 'inputPickup',
               'placeholder': 'Pickup Date',
               'append': 'fa fa-calendar',
               'input_toggle': True,
               'icon_toggle': True,
               }
    ), label='', disabled=True)
    personal_name = forms.CharField(widget=forms.TextInput(
                                attrs={'class': 'form-control mb-1',
                                       'id': 'inputPersonalName',
                                       'placeholder': 'Personal Name',
                                       }
                                ), label='', disabled=True)
    email = forms.EmailField(widget=forms.TextInput(
                                attrs={'class': 'form-control mb-1',
                                       'id': 'inputEmail',
                                       'placeholder': 'Email',
                                       }
                                ), label='', disabled=True)

    phone = forms.CharField(widget=forms.TextInput(
                                attrs={'class': 'form-control mb-1',
                                       'id': 'inputPhone',
                                       'placeholder': 'Phone number',
                                       }
                                ), label='', disabled=True)

    company = forms.ModelChoiceField(queryset=Company.objects.all(), empty_label='Company', label='', disabled=True)

    # class Meta:
    #     model = Cart
    #     fields = ('manifestation',
    #               'address',
    #               'beginning',
    #               'ending',
    #               'delivery',
    #               'pickup',
    #               'personal_name',
    #               'email',
    #               'phone'
    #               )
    #
    # def clean_beginning(self):
    #     beginning = self.cleaned_data.get('beginning')
    #     date_time_obj = datetime.datetime.strptime(beginning, '%d/%m/%Y %H:%M')
    #
    #     return date_time_obj
    #
    # def clean_ending(self):
    #     ending = self.cleaned_data.get('ending')
    #     date_time_obj = datetime.datetime.strptime(ending, '%d/%m/%Y %H:%M')
    #
    #     return date_time_obj
    #
    # def clean_delivery(self):
    #     delivery = self.cleaned_data.get('delivery')
    #     date_time_obj = datetime.datetime.strptime(delivery, '%d/%m/%Y %H:%M')
    #
    #     return date_time_obj
    #
    # def clean_pickup(self):
    #     pickup = self.cleaned_data.get('pickup')
    #     date_time_obj = datetime.datetime.strptime(pickup, '%d/%m/%Y %H:%M')
    #
    #     return date_time_obj

    # def save(self, commit=True):
    #     cart = super(CartForm, self).save(commit=False)
    #     if commit:
    #         cart.save()
    #         print('OVO SE POZIVA!!!')
    #     return cart

src/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect
from django.http import Http404, JsonResponse


from .models import Order


class AllOrdersView(LoginRequiredMixin, ListView):
    template_name = 'orders/home.html'

    def get_queryset(self):
        user = self.request.user
        return Order.objects.all(user)
        # return Order.objects.my_orders(self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(AllOrdersView, self).get_context_data(*args, **kwargs)
        return context


class OrderDetailView(DetailView):
    template_name = "orders/detail.html"

    def get_object(self, *args, **kwargs):
        xid = self.kwargs.get('id')
        try:
            instance = Order.objects.get(id=xid)

            # instance.form = OrderForm()
            #
            # str = instance.cart.delivery
            # # date_object = datetime.strptime(str, '%d/%m/%y %H:%m')
            # # print(date_object)
            # print(str.year)
            # print(str.strftime("%d/%m/%Y %H:%M"))
            #
            # form = OrderForm(initial={
            #                     'manifestation': instance.cart.manifestation,
            #                     'address': instance.cart.address,
            #                     'beginning': instance.cart.beginning,
            #                     'ending': instance.cart.ending,
            #                     'delivery': str.strftime("%d/%m/%Y %H:%M"),
            #                     'pickup': instance.cart.pickup,
            #                     'personal_name': instance.cart.personal_name,
            #                     'email': instance.cart.email,
            #                     'phone': instance.cart.phone
            #                 })
            #
            # instance.form = form
            #
            #
            # str = instance.cart.delivery
            # #date_object = datetime.strptime(str, '%d/%m/%y %H:%m')
            # #print(date_object)
            # print(str.year)
            # print(str.strftime("%d/%m/%Y %H:%M"))
        except Order.DoesNotExist:
            raise Http404("Order doesn't exist!")
        except Order.MultipleObjectsReturned:
            qs = Order.objects.filter(id=xid)
            instance = qs.first()
        except:
            raise Http404("Uhhh")
        return instance


@csrf_exempt
def order_confirm(request, id):
    user = request.user
    if user.is_authenticated and (user.is_staff or user.is_admin):
        order_id = id
        if order_id is not None:
            try:
                order_obj = Order.objects.get(id=order_id)
                if order_obj.status != 'confirm' and order_obj.status != 'canceled':
                    order_obj.status = 'confirm'
                    order_obj.save()
            except Order.DoesNotExist:
                return redirect('orders:home')
    return JsonResponse({})
    # return redirect('orders:home')


@csrf_exempt
def order_edit(request, id):
    user = request.user
    data = {}
    if user.is_authenticated:
        try:
            order_obj = Order.objects.get(id=id)
            cart_obj = order_obj.cart
            request.session['cart_id'] = cart_obj.id
            request.session['cart_items'] = cart_obj.products.count()

            data = {
                'refresh': 'true'
            }
        except Order.DoesNotExist:
            return redirect('orders:home')
    return JsonResponse(data)

src/orders/templates/orders/detail.html
{% extends 'base.html' %}
{% load static %}

{% block base_head %}
    <link rel="stylesheet" href="{% static 'css/tfl.css' %}">
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="mb-3">
      <i class="fas fa-dolly-flatbed"></i>
    </h1>

    <div class="row">
{#      <form method="POST" action="{% url 'cart:checkout' %}" class="form col-md-12" style="justify-content: center; display: flex;"> {% csrf_token %}#}
        <div class="col-md-6">
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Manifestation</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.manifestation }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend" >
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Address</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.address }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Beginning</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.beginning|date:'d/m/Y H:i' }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Ending</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.ending|date:'d/m/Y H:i' }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Delivery</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.delivery|date:'d/m/Y H:i' }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Pickup</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.pickup|date:'d/m/Y H:i' }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Person</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.personal_name }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Email</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.email }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Phone</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.phone }}">
            </div>
            <div class="input-group">
              <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2" style="width: 120px">Company</span>
              </div>
              <input type="text" class="form-control" id="validationDefaultUsername" disabled="true" value="{{ object.cart.company }}">
            </div>
            {% if request.user.is_staff %}
                {% if object.status != 'confirm' and object.status != 'canceled' %}
                    <button type="button" class="btn btn-info" onclick="confirm_order({{ object.id }})">Confirm</button>
                {% endif %}
                <button type="button" class="btn btn-info" onclick="order_edit({{ object.cart.id }})">Edit</button>
                <button type="button" class="btn btn-info">Cancel</button>
            {% endif %}
      </div>

      <div class="col-md-6">
        <div class="table-responsive-sm">
          <table class="table table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
{#                <th scope="col">Remove</th>#}
              </tr>
            </thead>
            <tbody>
              {% for p in object.cart.products.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                  <a href="{{p.product.get_absolute_url}}"> {{p.product.title}}</a>
                </td>
                <td>{{ p.quantity }}</td>
                <td>{{ p.product.price }}</td>
{#                <td>#}
{#                  <form method="POST" action="{% url 'cart:remove' %}" class="form" style="justify-content: center; display: flex;"> {% csrf_token %}#}
{#                    <input type="hidden" name="product_id" value="{{ p.product.id }}" />#}
{#                    <button type="submit" style="border: None; background: None"><i class="fas fa-trash-alt"></i></button>#}
{#                  </form>#}
{#                </td>#}
              </tr>
              {% endfor %}
              <tr>
                <td colspan="3"></td>
                <td>Weight: {{ object.cart.total_weight }}</td>
              </tr>
              <tr>
                <td colspan="3"></td>
                <td>Total: {{ object.cart.total_price }}</td>
              </tr>
{#              <tr>#}
{#                <td colspan="4"></td>#}
{#                <td>#}
{#                  <button type="submit" class="btn btn-lg btn-success">Checkout</button>#}
{#                </td>#}
{#              </tr>#}
            </tbody>
          </table>
        </div>
      </div>
{#    </form>#}
    </div>

{% endblock %}

src/orders/templates/orders/home.html
{% extends 'base.html' %}
{% load static %}

{% block base_head %}
    <link rel="stylesheet" href="{% static 'css/tfl.css' %}">
{% endblock %}

{% block content %}
    <h1 class="mb-3">
        <i class="fas fa-list-ul"></i>
    </h1>
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive-sm">
            <table class="table table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Manifestation</th>
                        <th scope="col">Delivery - Pickup</th>
                        <th scope="col">Status</th>
                        <th scope="col">Username</th>
                        <th scope="col">Created</th>
{#                        <th scope="col">Order ID</th>#}
{#                        <th scope="col"></th>#}
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{ obj.get_absolute_url }}">{{ obj.cart.manifestation }}</a></td>
                        <td>{{ obj.cart.delivery|date:"d F Y H:i" }} - {{ obj.cart.pickup|date:"d F Y H:i" }}</td>
                        <td>
                            {% if obj.status == 'created' %}
                                <i class="fas fa-check"></i>
                            {% elif obj.status == 'confirm' %}
                                <i class="fas fa-check-double"></i>
                            {% else %}
                                <i class="fas fa-times"></i>
                            {% endif %}
                        </td>
                        <td>{{ obj.cart.user.username }}</td>
                        <td>{{ obj.timestamp }}</td>
{#                        <td>{{ obj.id }}</td>#}
{#                        <td>#}
{#                            {% if request.user.is_admin or request.user.is_staff %}#}
{#                                {% if obj.status != 'confirm' and obj.status != 'canceled' %}#}
{#                                    <form method="POST" action="{% url 'orders:confirm' %}" class="form" style="justify-content: center; display: flex;"> {% csrf_token %}#}
{#                                        <input type="hidden" name="order_id" value="{{ obj.id }}" />#}
{#                                        <button type="submit" style="border: None; background: None">Confirm<i class="fas fa-check-double"></i></button>#}
{#                                    </form>#}
{#                                {% endif %}#}
{#                            {% endif %}#}
{#                        </td>#}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    </div>
{% endblock %}