src/posts/urls.py
from django.urls import path

from .views import (
    PostView,
    post_add,
    post_remove
)

app_name = 'post'

urlpatterns = [
    path('', PostView.as_view(), name='home'),
    path('add/', post_add, name='add'),
    path('remove/', post_remove, name='remove'),
]

src/tfl/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from .views import home_page
from accounts.views import LoginView, RegisterView
from products.views import ProductAddView
from dashboard.views import DashboardView, DashboardDataApiView


urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('add_product/', ProductAddView.as_view(), name='add_product'),
    path('api/dashboard/', DashboardDataApiView.as_view(), name='dashboard-api'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('register/', RegisterView.as_view(), name='register'),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
import random
import os
from django.conf import settings
from django.db import models


User = settings.AUTH_USER_MODEL


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3265456541)
    name, ext = get_filename_ext(filename)
    final_name = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return 'posts/{new_filename}/{final_name}'.format(
        new_filename=new_filename,
        final_name=final_name
    )


class PostQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True).order_by('-timestamp')


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def new(self, form, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
                image = form.cleaned_data['image']
                description = form.cleaned_data['description']
                return self.model.objects.create(user=user_obj, description=description, image=image)
        return None

    def remove(self, post_id):
        if post_id is not None and post_id != '':
            post_obj = self.get_by_id(post_id)
            if post_obj is not None:
                post_obj.active = False
                post_obj.save()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    description = models.CharField(max_length=2048, blank=True, null=True)
    image = models.ImageField(upload_to=upload_image_path, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    objects = PostManager()

    def __str__(self):
        return str(self.id)

src/posts/forms.py
from django import forms

from .models import Post
from tfl.forms import MyImagePostWidget


class PostForm(forms.ModelForm):
    image = forms.ImageField(widget=MyImagePostWidget(), label='', required=True)
    description = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-1',
               'id': 'inputDescription',
               'placeholder': 'Description',
               }
    ), label='', required=False)

    class Meta:
        model = Post
        fields = ('image', 'description')

    # def save(self, commit=True):
    #     post = super(PostForm, self).save(commit=False)
    #     print(self.request.user)
    #     # post.user = self.request.user
    #     if commit:
    #         post.save()
    #     return post

src/posts/views.py
from django.views.generic import ListView, FormView, CreateView, DeleteView
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponseServerError
from django.urls import reverse

from tfl.mixins import NextUrlMixin

from .models import Post
from .forms import PostForm


class PostView(ListView, FormView):
    form_class = PostForm
    template_name = "posts/home.html"
    #success_url = '/cart/'

    def get_queryset(self):
        return Post.objects.all()

    # def form_valid(self, form):
    #     form.save()
    #     return redirect(self.success_url)


# class PostAddView(CreateView):
#     form_class = PostForm
#     template_name = "posts/home.html"
#     success_url = '/cart/'
#
#
#     def get_queryset(self):
#         return Post.objects.all()

def post_add(request):
    if request.method == 'POST':
        success_url = '/'
        form = PostForm(request.POST or None, request.FILES or None)
        # print(form.is_valid())
        if form.is_valid():
            Post.objects.new(user=request.user, form=form)
            return redirect(success_url)
    return HttpResponseServerError('GRESKAAAAA')


def post_remove(request):
    user = request.user
    if request.method == 'POST' and (user.is_staff or user.is_admin):
        post_id = request.POST.get('post_id')
        if post_id is not None:
            Post.objects.remove(post_id)
    return redirect('/')


# class CartRemoveView(NextUrlMixin, DeleteView):
#     form_class = PostForm
#     template_name = 'posts/home.html'
#     success_url = '/'
#
#     def get_object(self, queryset=None):
#         request = self.request
#         post_id = request.POST.get('post_id')
#         if post_id is not None:
#             try:
#                 post_obj = Post.objects.get(id=post_id)
#                 post_obj.active = False
#                 post_obj.save()
#             except Post.DoesNotExist:
#                 return redirect('/')
#         return None
#
#     def get_success_url(self):
#         return reverse('/')

src/posts/templates/posts/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    {% if request.user.staff %}
        <form enctype="multipart/form-data" class="text-center" method="POST" action="{% url 'post:add' %}"> {% csrf_token %}
            <div class="row">
                <div class="col-sm-2 mt-5"></div>
                <div class="col-sm-8 mt-5" style="text-align: left;">
                    {{ form.as_p }}
                </div>
                <div class="col-sm-2 mt-5"></div>
            </div>
            <div class="row">
                <div class="col-sm-2 mt-1"></div>
                <div class="col-sm-2 mt-1">
                    <button class="btn btn-lg btn-dark btn-block" type="submit">Submit news...</button>
                </div>

            </div>
        </form>
    {% endif %}
    <div class="card-deck">
        <div class="row">
            {% for obj in object_list %}
                <div class="col-sm-2 mt-5"></div>
                <div class="col-sm-8 mt-5">
                    {% include 'posts/snippets/card.html' with instance=obj %}
                </div>
                <div class="col-sm-2 mt-5">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_admin or request.user.is_staff %}
                        <form enctype="multipart/form-data" class="text-left" method="POST" action="{% url 'post:remove' %}"> {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{ obj.id }}" />
                            <button type="submit" style="border: None; background: None; color: red;" title="Remove"><i class="fas fa-times"></i></button>
                        </form>
                    {% endif %}
                {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}